---
name: Updatecli

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 6'

permissions:
  pull-requests: write
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@current

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@9b35aa663a924d5d5faf89dac76594e3034bcf1f # v2.56.0

      - name: Run Updatecli
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: updatecli apply --config .github/updatecli.d/
